fsb.smartcontract/fsb.smartcontract/Controllers/LeaveRequestController.cs
using fsb.smartcontract.Services.LeaveRequest;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Model.LeaveRequest;
using Model.Requests;
using Model.Response;
using NToastNotify;
using System.Net.Http;

namespace fsb.smartcontract.Controllers
{
    public class LeaveRequestController : BaseController
    {
        private readonly ILogger<LeaveRequestController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILeaveRequestService _leaveRequestService;

        public LeaveRequestController(
            ILogger<LeaveRequestController> logger,
            IHttpClientFactory factory,
            IToastNotification toastNotification,
            IHttpContextAccessor httpContextAccessor,
            ILeaveRequestService leaveRequestServiceService
            ) : base(factory)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _httpContextAccessor = httpContextAccessor;
            _leaveRequestService = leaveRequestServiceService;
        }

        [Route("danh-sach-nghi-phep")]
        public IActionResult LeaveRequests()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetListLeaveRequest(string searchValue)
        {
            SearchLeaveRequestModel searchModel = talbeSearchModel.Get<SearchLeaveRequestModel>();
            searchModel.SearchValue = searchValue;
            var data = _leaveRequestService.GetListLeaveRequest(searchModel);
            if (data.Code != StatusCodes.Status200OK)
                _toastNotification.AddErrorToastMessage(data.Message);
            return Json(data);
        }

        [Route("tao-moi-nghi-phep")]
        public IActionResult CreateLeaveRequest()
        {
            ViewBag.GetListClassForCombo = _leaveRequestService.GetListClassForCombo();
            return View();
        }

        [HttpPost]
        public IActionResult InsertLeaveRequest(LeaveRequestModel model)
        {
            var res = _leaveRequestService.CreateLeaveRequest(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [Route("chi-tiet-nghi-phep/{id}")]
        public IActionResult ViewLeaveRequest(int Id)
        {
            ViewBag.GetListClassForCombo = _leaveRequestService.GetListClassForCombo();
            var model = new LeaveRequestModel();
            model.Id = Id;
            var res = _leaveRequestService.GetLeaveRequestById(model);

            if (res == null)
                res = new Response<LeaveRequestModel>();
            if (res.Data == null)
                res.Data = new LeaveRequestModel();

            return View(res.Data);
        }

        [HttpPost]
        public IActionResult UpdateStatusLeaveRequest(LeaveRequestModel model)
        {
            var res = _leaveRequestService.UpdateStatusLeaveRequest(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [Route("sua-nghi-phep/{id}")]
        public IActionResult EditLeaveRequest(int Id)
        {
            ViewBag.GetListClassForCombo = _leaveRequestService.GetListClassForCombo();
            var model = new LeaveRequestModel();
            model.Id = Id;
            var res = _leaveRequestService.GetLeaveRequestById(model);

            if (res == null)
                res = new Response<LeaveRequestModel>();
            if (res.Data == null)
                res.Data = new LeaveRequestModel();

            return View(res.Data);
        }

        [HttpPost]
        public IActionResult UpdateLeaveRequest(LeaveRequestModel model)
        {
            var res = _leaveRequestService.UpdateLeaveRequest(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [HttpPost]
        public IActionResult DeleteLeaveRequest(LeaveRequestModel model)
        {
            var res = _leaveRequestService.DeleteLeaveRequest(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }
    }
}

fsb.smartcontract/fsb.smartcontract/Views/LeaveRequest/CreateLeaveRequest.cshtml
@model Model.LeaveRequest.LeaveRequestModel
@{
    ViewData["Title"] = "CreateLeaveRequest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Thêm mới nghỉ phép</h1>

        <div class="form-group"></div>
        <form id="CreatePlace" action="#" method="post">
            <div class="col-lg-12 col-xl-8">
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tên học viên<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="StudentName" class="form-control" type="text" placeholder="Nhập tên học viên" />
                        <span asp-validation-for="StudentName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Lớp<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <select asp-for="ClassId" class="form-control listClass" asp-items="@ViewBag.GetListClassForCombo">
                            <option>Chọn...</option>
                        </select>
                        <span asp-validation-for="ClassId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tiêu đề<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="Title" class="form-control" type="text" placeholder="Nhập tiêu đề" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Ngày nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="LeaveDate" class="form-control" type="datetime-local" />
                        <span asp-validation-for="LeaveDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Loại nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input type="radio" name="fav_LeaveType" id="LateComing" value="1"> 
                        <label for="LateComing">Late Coming</label>
                        <input type="radio" name="fav_LeaveType" id="EarlyLeave" value="2">
                        <label for="EarlyLeave">Early Leave</label>
                        <input type="radio" name="fav_LeaveType" id="LeaveHaft" value="3">
                        <label for="LateComing">Leave a haft of day</label>
                        <input type="radio" name="fav_LeaveType" id="LeaveOne" value="4">
                        <label for="LeaveOne">Leave one day</label>
                        <span asp-validation-for="LeaveType" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Lý do nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <textarea asp-for="ReasonLeave" class="form-control" type="text" ></textarea>
                        <span asp-validation-for="ReasonLeave" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-6">
                <a href="@Url.Action("LeaveRequests", "LeaveRequest")" class="btn btn-secondary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Quay lại</span>
                </a>
                <a class="btn btn-success btn-icon-split" onclick="SaveLeaveRequest()">
                    <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Tạo mới</span>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function (){
        $(".listClass").select2({
            placeholder: "Chọn...",
            allowClear: true
        });

        //alert($('input[name="fav_LeaveType"]:checked').val())
    });

    function SaveLeaveRequest() {
        var lstIdStr = 'StudentName,Title,ClassId,LeaveDate,ReasonLeave';
        if (!RequireValidate(lstIdStr)) {
            toastr.error('Bạn chưa nhập đủ thông tin.');
            return;
        };

        var formData = new FormData();
        formData.append("StudentName", $("#StudentName").val());
        formData.append("ClassId", $("#ClassId").val());
        formData.append("Title", $("#Title").val());
        formData.append("LeaveDate", $("#LeaveDate").val());
        formData.append("LeaveType", $('input[name="fav_LeaveType"]:checked').val());
        formData.append("ReasonLeave", $("#ReasonLeave").val());
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("InsertLeaveRequest")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-nghi-phep';
                    }, 1000);
            }
        });
    }
</script>

fsb.smartcontract/fsb.smartcontract/Views/LeaveRequest/EditLeaveRequest.cshtml
@model Model.LeaveRequest.LeaveRequestModel
@{
    ViewData["Title"] = "EditLeaveRequest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Chi tiết nghỉ phép</h1>

        <div class="form-group"></div>
        <form id="CreatePlace" action="#" method="post">
            <div class="col-lg-12 col-xl-8">
                <input asp-for="Id" type="hidden" />
                <input asp-for="LeaveType" type="hidden"/>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tên học viên<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="StudentName" class="form-control" type="text" placeholder="Nhập tên học viên"/>
                        <span asp-validation-for="StudentName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Lớp<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <select asp-for="ClassId" class="form-control listClass" asp-items="@ViewBag.GetListClassForCombo">
                            <option>Chọn...</option>
                        </select>
                        <span asp-validation-for="ClassId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tiêu đề<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="Title" class="form-control" type="text" placeholder="Nhập tiêu đề"/>
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Ngày nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="LeaveDate" class="form-control" type="datetime-local"/>
                        <span asp-validation-for="LeaveDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Loại nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input type="radio" name="fav_LeaveType" id="LateComing" value="1">
                        <label for="LateComing">Late Coming</label>
                        <input type="radio" name="fav_LeaveType" id="EarlyLeave" value="2">
                        <label for="EarlyLeave">Early Leave</label>
                        <input type="radio" name="fav_LeaveType" id="LeaveHaft" value="3">
                        <label for="LateComing">Leave a haft of day</label>
                        <input type="radio" name="fav_LeaveType" id="LeaveOne" value="4">
                        <label for="LeaveOne">Leave one day</label>
                        <span asp-validation-for="LeaveType" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Lý do nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <textarea asp-for="ReasonLeave" class="form-control" type="text"></textarea>
                        <span asp-validation-for="ReasonLeave" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-6">
                <a class="btn btn-success btn-icon-split" onclick="SaveLeaveRequest()">
                    <span class="text">Lưu</span>
                </a>
                <a href="@Url.Action("LeaveRequests", "LeaveRequest")" class="btn btn-secondary btn-icon-split">
                    <span class="text">Quay lại</span>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function (){
        $(".listClass").select2({
            placeholder: "Chọn...",
            allowClear: true
        });

        var checkLeaveType = $('#LeaveType').val();
        $("input[name=fav_LeaveType][value=" + checkLeaveType + "]").prop('checked', true);
    });

    function SaveLeaveRequest(){
        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("StudentName", $("#StudentName").val());
        formData.append("ClassId", $("#ClassId").val());
        formData.append("LeaveDate", $("#LeaveDate").val());
        formData.append("LeaveType", $('input[name="fav_LeaveType"]:checked').val());
        formData.append("ReasonLeave", $("#ReasonLeave").val());
        formData.append("Title", $("#Title").val());
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("UpdateLeaveRequest")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-nghi-phep';
                    }, 1000);
            }
        });
    }
</script>

fsb.smartcontract/fsb.smartcontract/Views/LeaveRequest/LeaveRequests.cshtml
@{
    ViewData["Title"] = "LeaveRequests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Danh sách nghỉ phép</h1>
        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-12">
                <a href="@Url.Action("CreateLeaveRequest", "LeaveRequest")" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Thêm mới</span>
                </a>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="form-group row" style="justify-content: flex-end">
                    <div class="col-md-12 col-lg-3 pr-0">
                        <input id="searchValue" class="form-control searchValue" type="text" placeholder="Tìm kiếm" />
                    </div>
                    <a class="btn btn-success btn-icon-split" onclick="reloadWithPageOne()">
                        <span class="icon text-white-50">
                            <i class="fas fa-search"></i>
                        </span>
                    </a>
                </div>
                <table class="table table-bordered" id="monthPlanningTbl" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-orderable="false">Tên học viên</th>
                            <th data-orderable="false">Lớp</th>
                            <th data-orderable="false">Lý do</th>
                            <th data-orderable="false">Ngày nghỉ phép</th>
                            <th data-orderable="false">Loại nghỉ phép</th>
                            <th data-orderable="false">Trạng thái</th>
                            <th data-orderable="false">Thao tác</th>
                        </tr>
                    </thead>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Bạn muốn xóa bản ghi này không?</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                <a class="btn btn-danger" onclick="DeleteLeaveRequest()">Xóa</a>
            </div>
        </div>
    </div>
</div>
<script>
    var table = undefined;
    $(document).ready(function () {
        loadTable();
        $('#searchValue').keypress(function (e) {
            if (e.which == 13) {
                reloadWithPageOne();
            }
        });
    });
    function reloadWithPageOne() {
        if (table != undefined && table.api().ajax != undefined)
            table.api().ajax.reload(null, true);
    }
    function reload() {
        if (table != undefined && table.api().ajax != undefined)
            table.api().ajax.reload(null,false);
    }
    function loadTable() {
        table = $('#monthPlanningTbl').dataTable({
            "oLanguage": {
                "sEmptyTable": "Không có nghỉ phép"
            },
            "language": {
                "paginate": {
                    "previous": "Trước",
                    "next": "Tiếp theo"
                }
            },
            searching: false,
            paging: true,
            lengthChange: false,
            ordering: true,
            filter: false,
            destroy: true,
            orderMulti: false,
            serverSide: true,
            processing: true,
            lengthChange: false,
            "bSort": false,
            ajax: function (data, callback, settings) {
                data.searchValue = $('#searchValue').val();
                postTable("@Url.Action("GetListLeaveRequest", "LeaveRequest")", data, callback);
            },
            "columns": [
                { "data": "studentName", "name": "StudentName", "class": "studentName" },
                { "data": "className", "name": "ClassName", "class": "className" },
                { "data": "title", "name": "Title", "class": "title" },
                { "data": "leaveDate", "name": "LeaveDate", "class": "leaveDate" },
                { "data": "leaveTypeName", "name": "LeaveTypeName", "class": "leaveTypeName" },
                { "data": "statusName", "name": "StatusName", "class": "statusName" },
                {
                    "class": "action",
                    "render": function (data, row, full) {
                        return "<a class='fas fa-fw fa-eye' title='Chi tiết' onclick=ViewLeaveRequest('" + full.id + "'); ></a> <a href='#' class='fas fa-fw fa-trash' style='color:red' title='Xóa' data-toggle='modal' data-target='#deleteModal' onclick=openConfirmDelete('" + full.id + "');></a>";
                    }
                }
            ]
        });
    }

    function openConfirmDelete(id) {
        deleteId = id;
    }

    function DeleteLeaveRequest() {
        var formData = new FormData();
        formData.append("Id", deleteId);
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("DeleteLeaveRequest")', formData, function (data) {
            $('#deleteModal').modal("hide");
            reload();
        });
    }

    function ViewLeaveRequest(id) {
        location.href = '/chi-tiet-nghi-phep' + "/" + id;
    }
</script>

fsb.smartcontract/fsb.smartcontract/Views/LeaveRequest/ViewLeaveRequest.cshtml
@model Model.LeaveRequest.LeaveRequestModel
@{
    ViewData["Title"] = "ViewLeaveRequest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Chi tiết nghỉ phép</h1>

        <div class="form-group"></div>
        <form id="CreatePlace" action="#" method="post">
            <div class="col-lg-12 col-xl-8">
                <input asp-for="Id" type="hidden" />
                <input asp-for="LeaveType" type="hidden"/>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tên học viên<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="StudentName" class="form-control" type="text" placeholder="Nhập tên học viên" disabled/>
                        <span asp-validation-for="StudentName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Lớp<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <select asp-for="ClassId" class="form-control listClass" asp-items="@ViewBag.GetListClassForCombo" disabled>
                            <option>Chọn...</option>
                        </select>
                        <span asp-validation-for="ClassId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tiêu đề<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="Title" class="form-control" type="text" placeholder="Nhập tiêu đề" disabled/>
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Ngày nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="LeaveDate" class="form-control" type="datetime-local" disabled/>
                        <span asp-validation-for="LeaveDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Loại nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input type="radio" name="fav_LeaveType" id="LateComing" value="1" disabled>
                        <label for="LateComing">Late Coming</label>
                        <input type="radio" name="fav_LeaveType" id="EarlyLeave" value="2" disabled>
                        <label for="EarlyLeave">Early Leave</label>
                        <input type="radio" name="fav_LeaveType" id="LeaveHaft" value="3" disabled>
                        <label for="LateComing">Leave a haft of day</label>
                        <input type="radio" name="fav_LeaveType" id="LeaveOne" value="4" disabled>
                        <label for="LeaveOne">Leave one day</label>
                        <span asp-validation-for="LeaveType" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Lý do nghỉ phép<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <textarea asp-for="ReasonLeave" class="form-control" type="text" disabled></textarea>
                        <span asp-validation-for="ReasonLeave" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-6">
                <a class="btn btn-secondary btn-icon-split" onclick="EditLeaveRequest()">
                    <span class="text">Sửa</span>
                </a>
                <a class="btn btn-danger btn-icon-split" onclick="CancelLeaveRequest()">
                    <span class="text">Hủy</span>
                </a>
                <a class="btn btn-success btn-icon-split" onclick="ApproveLeaveRequest()">
                    <span class="text">Đồng ý</span>
                </a>
                <a class="btn btn-warning btn-icon-split" onclick="RejectLeaveRequest()">
                    <span class="text">Từ chối</span>
                </a>
                <a href="@Url.Action("LeaveRequests", "LeaveRequest")" class="btn btn-secondary btn-icon-split">
                    <span class="text">Quay lại</span>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function (){
        $(".listClass").select2({
            placeholder: "Chọn...",
            allowClear: true
        });

        var checkLeaveType = $('#LeaveType').val();
        $("input[name=fav_LeaveType][value=" + checkLeaveType + "]").prop('checked', true);
    });

    function EditLeaveRequest(){
       location.href = '/sua-nghi-phep' + "/" + $("#Id").val();
    }
    function CancelLeaveRequest(){
        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("Status", 2);
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("UpdateStatusLeaveRequest")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-nghi-phep';
                    }, 1000);
            }
        });
    }
    function ApproveLeaveRequest(){
        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("Status", 3);
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("UpdateStatusLeaveRequest")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-nghi-phep';
                    }, 1000);
            }
        });
    }
    function RejectLeaveRequest(){
        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("Status", 4);
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("UpdateStatusLeaveRequest")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-nghi-phep';
                    }, 1000);
            }
        });
    }
</script>