fsb.smartcontract/fsb.smartcontract/Controllers/CompanyController.cs
using fsb.smartcontract.Services.Company;
using fsb.smartcontract.Services.Role;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Model.Company;
using Model.Requests;
using Model.Response;
using NToastNotify;
using System.Net.Http;

namespace fsb.smartcontract.Controllers
{
    public class CompanyController : BaseController
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICompanyService _companyService;

        public CompanyController(
            ILogger<CompanyController> logger,
            IHttpClientFactory factory,
            IToastNotification toastNotification,
            IHttpContextAccessor httpContextAccessor,
            ICompanyService companyService
            ) : base(factory)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _httpContextAccessor = httpContextAccessor;
            _companyService = companyService;
        }

        [Route("danh-sach-cong-ty")]
        public IActionResult Companies()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetListCompany(string searchValue)
        {
            SearchCompanyModel searchModel = talbeSearchModel.Get<SearchCompanyModel>();
            searchModel.SearchValue = searchValue;
            var data = _companyService.GetListCompany(searchModel);
            if (data.Code != StatusCodes.Status200OK)
                _toastNotification.AddErrorToastMessage(data.Message);
            return Json(data);
        }

        [Route("them-moi-cong-ty")]
        public IActionResult CreateCompany()
        {
            return View();
        }

        [HttpPost]
        public IActionResult InsertCompany(CompanyModel model)
        {
            var res = _companyService.CreateCompany(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [HttpPost]
        public IActionResult DeleteCompany(int Id)
        {
            var model = new CompanyModel();
            model.Id = Id;
            var res = _companyService.DeleteCompany(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [Route("sua-cong-ty/{id}")]
        public IActionResult EditCompany(int Id)
        {
            var model = new CompanyModel();
            model.Id = Id;
            var res = _companyService.GetCompanyById(model);

            if (res == null)
                res = new Response<CompanyModel>();
            if (res.Data == null)
                res.Data = new CompanyModel();

            return View(res.Data);
        }

        [HttpPost]
        public IActionResult UpdateCompany(CompanyModel model)
        {
            var res = _companyService.UpdateCompany(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }
    }
}

fsb.smartcontract/fsb.smartcontract/Controllers/RoleController.cs
using fsb.smartcontract.Services.Role;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Model.Requests;
using Model.Response;
using Model.Role;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace fsb.smartcontract.Controllers
{
    public class RoleController : BaseController
    {
        private readonly ILogger<RoleController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IRoleService _roleService;

        public RoleController(
            ILogger<RoleController> logger,
            IHttpClientFactory factory,
            IToastNotification toastNotification,
            IHttpContextAccessor httpContextAccessor,
            IRoleService roleService
            ) : base(factory)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _httpContextAccessor = httpContextAccessor;
            _roleService = roleService;
        }

        [Route("danh-sach-nhom-quyen")]
        public IActionResult Roles()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetListRole(string searchValue)
        {
            SearchRoleModel searchModel = talbeSearchModel.Get<SearchRoleModel>();
            searchModel.SearchValue = searchValue;
            var data = _roleService.GetListRole(searchModel);
            if (data.Code != StatusCodes.Status200OK)
                _toastNotification.AddErrorToastMessage(data.Message);
            return Json(data);
        }

        [Route("them-moi-nhom-quyen")]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public IActionResult InsertRole(RoleModel model)
        {
            var res = _roleService.CreateRole(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [HttpPost]
        public IActionResult DeleteRole(Guid Id)
        {
            var model = new RoleModel();
            model.Id = Id;
            model.UpdateBy = _SessionUser.Id;
            var res = _roleService.DeleteRole(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [Route("sua-nhom-quyen/{id}")]
        public IActionResult EditRole(Guid Id)
        {
            var model = new RoleModel();
            model.Id = Id;
            var res = _roleService.GetRoleById(model);

            if (res == null)
                res = new Response<RoleModel>();
            if (res.Data == null)
                res.Data = new RoleModel();

            return View(res.Data);
        }

        [HttpPost]
        public IActionResult UpdateRole(RoleModel model)
        {
            var res = _roleService.UpdateRole(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }
    }
}

fsb.smartcontract/fsb.smartcontract/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;

namespace fsb.smartcontract.Controllers
{
    public class StaffController : BaseController
    {
        private readonly ILogger<StaffController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public StaffController(
            ILogger<StaffController> logger,
            IHttpClientFactory factory,
            IToastNotification toastNotification,
            IHttpContextAccessor httpContextAccessor
            ) : base(factory)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Staffs()
        {
            return View();
        }
    }
}

fsb.smartcontract/fsb.smartcontract/Controllers/UserController.cs
using fsb.smartcontract.Services.Role;
using fsb.smartcontract.Services.User;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace fsb.smartcontract.Controllers
{
    public class UserController : BaseController
    {
        private readonly ILogger<UserController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IRoleService _roleService;
        private readonly IUserService _userService;

        public UserController(
            ILogger<UserController> logger,
            IHttpClientFactory factory,
            IToastNotification toastNotification,
            IHttpContextAccessor httpContextAccessor,
            IRoleService roleService,
            IUserService userService
            ) : base(factory)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _httpContextAccessor = httpContextAccessor;
            _roleService = roleService;
            _userService = userService;
        }

        public IActionResult Users()
        {
            return View();
        }
    }
}

fsb.smartcontract/fsb.smartcontract/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@using fsb.smartcontract.Common
@using Common.Constants
@using Common
@using Model.UserInfo
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FSB Smart Contract</title>

    <!-- Custom fonts for this template-->
    <link href="~/fonts/fontawesome-free/css/all.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet" />
    <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <!-- Select2 CSS -->
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" />
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <!-- Page level plugins -->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <!-- Page level custom scripts -->
    <script src="~/js/demo/datatables-demo.js"></script>
    <script src="~/vendor/datatables/dataTables.rowGroup.min.js"></script>
    <!-- Select2 -->
    <script src="~/vendor/select2/select2.min.js"></script>
    <script src="~/js/CommonHelper.js"></script>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Dashboard","Home")">
                <div class="sidebar-brand-text mx-3">Smart Contract</div>
            </a>

            @await Html.PartialAsync("_NavMenu")

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small" id="head-username"></span>
                                <img class="img-profile rounded-circle" src="~/image/ic_user.png">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Đăng xuất
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <form method="POST" action="/" hidden>
                    @Html.AntiForgeryToken()
                </form>
                <div>
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; 2020. Made by VinSoftware.</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Đăng xuất</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Chọn "Đăng xuất" bên dưới nếu bạn đã sẵn sàng kết thúc phiên hiện tại của mình.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                    <a class="btn btn-primary" href="@Url.Action("ActionLogout","Account")">Đăng xuất</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal placeholder -->
    <div id="modal-placeholder"></div>

    @*<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script>
        var _token = $('input[name="__RequestVerificationToken"]').val();
        $(document).ready(function () {
            $.get('@Url.Action("GetUserInfo", "Account")', function (data) {
                if (data != null) {
                    $('#head-username').text(data.fullName);

                    //var checkUserRoleName = data.userRoleName;
                    //var checkIsReportBudget = data.isReportBudget;
                    //var checkIsUploadBudget = data.isUploadBudget;

                    //$('#check-dashboard').hide();
                    //$('#check-line-departmentplannings').hide();
                    //$('#check-departmentplannings').hide();
                    //$('#check-line-reportdepartmentplanning').hide();
                    //$('#check-reportdepartmentplanning').hide();
                    //$('#check-line-users').hide();
                    //$('#check-users').hide();
                    //$('#check-masterdata').hide();
                    //$('#check-monthPlannings').hide();
                    //$('#check-budgets').hide();
                    //$('#check-reportBudget').hide();

                    //if (checkUserRoleName == "admin") {
                    //    $('#check-dashboard').show();
                    //    $('#check-line-departmentplannings').show();
                    //    $('#check-departmentplannings').show();
                    //    $('#check-line-reportdepartmentplanning').show();
                    //    $('#check-reportdepartmentplanning').show();
                    //    $('#check-line-users').show();
                    //    $('#check-users').show();
                    //    $('#check-masterdata').show();
                    //    $('#check-monthPlannings').show();
                    //    $('#check-budgets').show();
                    //    $('#check-reportBudget').show();
                    //}
                    //if (checkUserRoleName == "accountant_bp") {
                    //    $('#check-dashboard').show();
                    //    $('#check-line-departmentplannings').show();
                    //    $('#check-departmentplannings').show();
                    //}
                    //if (checkUserRoleName == "accountant_ho") {
                    //    $('#check-dashboard').show();
                    //    $('#check-line-departmentplannings').show();
                    //    $('#check-departmentplannings').show();
                    //    $('#check-line-reportdepartmentplanning').show();
                    //    $('#check-reportdepartmentplanning').show();
                    //}
                    //if (checkUserRoleName == "accountant_institute") {
                    //    $('#check-budgets').show();
                    //    $('#check-reportBudget').show();
                    //}

                    //if (checkIsUploadBudget == true) {
                    //    $('#check-budgets').show();
                    //}
                    //if (checkIsReportBudget == true) {
                    //    $('#check-reportBudget').show();
                    //}
                }
            })
        });
    </script>
    @await Component.InvokeAsync("NToastNotify")
</body>

</html>

fsb.smartcontract/fsb.smartcontract/Views/Shared/_LayoutChangePassword.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@using fsb.smartcontract.Common
@using Common.Constants
@using Common
@using Model.UserInfo
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VinFast Financial Plan</title>

    <!-- Custom fonts for this template-->
    <link href="~/fonts/fontawesome-free/css/all.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet" />
    <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <!-- Select2 CSS -->
    <link href="~/vendor/select2/select2.min.css" rel="stylesheet" />
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <!-- Page level plugins -->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <!-- Page level custom scripts -->
    <script src="~/js/demo/datatables-demo.js"></script>

    <!-- Select2 -->
    <script src="~/vendor/select2/select2.min.js"></script>
    <script src="~/js/CommonHelper.js"></script>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Dashboard","Home")">
                <div class="sidebar-brand-icon rotate-n-15">
                    @*<img style="width: 300px; height: 150px;" src="~/image/logo-vinpearl.jpg" />*@
                </div>
                <div class="sidebar-brand-text mx-3">VinFast</div>
            </a>

            @*@await Html.PartialAsync("_NavMenu")*@

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Html.Raw(HttpContextAccessor.HttpContext.Session.GetObject<UserViewModel>(Common.Constants.LoginConstant.PERSON_INFO_SESSION).FullName)</span>
                                <img class="img-profile rounded-circle" src="~/image/ic_user.png">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Đăng xuất
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <form method="POST" action="/" hidden>
                    @Html.AntiForgeryToken()
                </form>
                <div>
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; 2020. Made by Vinsoftware.</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Đăng xuất</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Chọn "Đăng xuất" bên dưới nếu bạn đã sẵn sàng kết thúc phiên hiện tại của mình.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                    <a class="btn btn-primary" href="@Url.Action("ActionLogout","Account")">Đăng xuất</a>
                </div>
            </div>
        </div>
    </div>


    @*<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script>
        var _token = $('input[name="__RequestVerificationToken"]').val();
        $(document).ready(function () {
            $.get('@Url.Action("GetUserInfo", "Account")', function (data) {
                if (data != null) {

                    //var cAdmin = data.isAdmin;
                    var checkUserRoleName = data.userRoleName;
                    $('#check-dashboard').hide();
                    $('#check-users').hide();
                    $('#check-departmentplannings').hide();
                    $('#check-reportdepartmentplanning').hide();
                    $('#check-line-dashboard').hide();
                    $('#check-line-departmentplannings').hide();
                    $('#check-line-reportdepartmentplanning').hide();

                    if (checkUserRoleName == "admin") {
                        $('#check-dashboard').show();
                        $('#check-line-dashboard').show();
                        $('#check-users').show();
                    }
                    if (checkUserRoleName == "accountant_bp") {
                        $('#check-dashboard').show();
                        $('#check-line-dashboard').show();
                        $('#check-departmentplannings').show();
                    }
                    if (checkUserRoleName == "accountant_ho") {
                        $('#check-dashboard').show();
                        $('#check-line-dashboard').show();
                        $('#check-departmentplannings').show();
                        $('#check-line-departmentplannings').hide();
                        $('#check-reportdepartmentplanning').show();
                    }
                }
            })
        });
    </script>
    @await Component.InvokeAsync("NToastNotify")
</body>

</html>

fsb.smartcontract/fsb.smartcontract/Views/Shared/_NavMenu.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@using Common.Constants
@using Common
<!-- Divider -->
<hr class="sidebar-divider my-0">


<!-- Nav Item - Dashboard -->
<li class="nav-item active" id="check-dashboard">
    <a class="nav-link" href="@Url.Action("Dashboard", "Home")">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Bảng điều khiển</span>
    </a>
</li>

<!-- Người dùng -->
<hr class="sidebar-divider" id="check-line-users">
<li class="nav-item" id="check-users">
    <a class="nav-link" href="@Url.Action("LeaveRequests","LeaveRequest")">
        <i class="fas fa-fw fa-cog"></i>
        <span>Quản lý nghỉ phép</span>
    </a>
</li>
<li class="nav-item" id="check-users">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne"
       aria-expanded="true" aria-controls="collapseOne">
        <i class="fas fa-fw fa-cog"></i>
        <span>Quản lý người dùng</span>
    </a>
    <div id="collapseOne" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="@Url.Action("Roles", "Role")">Quản lý nhóm quyền</a>
            <a class="collapse-item" href="@Url.Action("Users", "User")">Quản lý tài khoản</a>
        </div>
    </div>
</li>
<li class="nav-item" id="check-info">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
       aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-fw fa-cog"></i>
        <span>Quản lý thông tin</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="@Url.Action("Companies", "Company")">Quản lý công ty</a>
            <a class="collapse-item" href="@Url.Action("Departments", "Department")">Quản lý bộ phận</a>
            <a class="collapse-item" href="@Url.Action("TypeDocuments", "TypeDocument")">Quản lý loại tài liệu</a>
        </div>
    </div>
</li>
<li class="nav-item" id="check-employee">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree"
       aria-expanded="true" aria-controls="collapseThree">
        <i class="fas fa-fw fa-cog"></i>
        <span>Quản lý nhân sự</span>
    </a>
    <div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="@Url.Action("Staffs", "Staff")">Quản lý thông tin nhân sự</a>
            <a class="collapse-item" href="@Url.Action("Contracts", "Contract")">Quản lý danh sách hợp đồng</a>
        </div>
    </div>
</li>

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">